PREFIX rov:    <http://www.w3.org/ns/regorg#>
PREFIX schema: <http://schema.org/>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?domain
WHERE {
  GRAPH <http://linked.opendata.cz/resource/dataset/isvz.cz> {
    ?organization a schema:Organization ;
      schema:url ?url .
    FILTER NOT EXISTS {
      ?organization rov:registration/skos:inScheme <http://linked.opendata.cz/resource/concept-scheme/CZ-ICO> .
    }
    FILTER CONTAINS(?url, ".cz")
    BIND (REPLACE(?url, "^[a-z]+:\\/\\/(www\\.)?([^/]+).*$", "$2") AS ?domain)
  }
}
